---
abstract: 'A date and time object'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Module::Build: 0.3601
  Storable: 0
  Test::Fatal: 0
  Test::More: 0.88
  Test::Warnings: 0.005
  utf8: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime
requires:
  Carp: 0
  DateTime::Locale: 0.41
  DateTime::TimeZone: 1.09
  POSIX: 0
  Params::Validate: 0.76
  Scalar::Util: 0
  Try::Tiny: 0
  XSLoader: 0
  base: 0
  constant: 0
  integer: 0
  overload: 0
  perl: 5.008001
  strict: 0
  vars: 0
  warnings: 0
  warnings::register: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DateTime
  repository: git://git.urth.org/DateTime.pm.git
version: 1.10
x_authority: cpan:DROLSKY
