
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
DROLSKY
DROLSKY's
Rolsky
Rolsky's
Anno
BCE
CLDR
CPAN
DATETIME
DateTime
DateTimes
Datetime
Datetimes
Domini
EEEE
EEEEE
Flávio
Formatters
GGGG
GGGGG
Glock
IEEE
LLL
LLLL
LLLLL
Liang's
MMM
MMMM
MMMMM
Measham's
POSIX
PayPal
QQQ
QQQQ
Rata
SU
Soibelmann
Storable
TZ
Tsai
UTC
VVVV
ZZZZ
ZZZZZ
afterwards
bian
ccc
cccc
ccccc
conformant
datetime
datetime's
datetimes
decrement
dian
durations
eee
eeee
eeeee
fallback
formatter
hh
iCal
ji
mutiplication
na
namespace
ni
nitty
other's
proleptic
qqq
qqqq
sexagesimal
subclasses
uu
vvvv
wiki
yy
yyyy
yyyyy
zzzz
Dave
autarch
Doug
Bell
madcityzen
Ricardo
Signes
rjbs
devnull
chansen
convert
fglock
fiji
jhoblitt
koschei
lestrrat
rbowen
rkhill
unknown
wheeler
lib
Duration
Helpers
DateTimePP
DateTimePPExtra
Infinite
LeapSecond
